#-------------------------------
# Site Settings
title: Jube
logo: '/images/logo.png'
description: Jube is open-source transaction and event monitoring software.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Software'
      url: 'https://github.com/jube-home/jube'
    - title: 'Documentation'
      url: 'https://jube-home.github.io/jube/'
    - title: 'Support'
      url: '/support/'

#-------------------------------
# Author Settings
author:
  author__name: Information about the author of Jube
  author__bio: Richard Churchman, a seasoned Cloud Architect and Software Developer, is the author, caretaker, and advocate behind Jube. With expertise in implementing high throughput real-time transaction and event monitoring systems, Richard operates at the intersection of Software Engineering, Data Engineering, and Machine Learning.
  author__avatar: '/images/Jube.png'

social:
- {icon: "ion-logo-github", link: "https://github.com/jube-home/jube"}
- {icon: "ion-logo-twitter", link: "https://twitter.com/JubeHome"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
hero:
  hero__title: Open-Source Transaction and Event Monitoring Software
  hero__description: Jube is an open-source software designed for monitoring transactions and events. It offers a range of powerful features including real-time data wrangling, artificial intelligence, decision making, and case management. Jube's exceptional performance is particularly evident in its application to fraud prevention and abuse detection scenarios.
  hero__image: '/images/Jube.png'

#-------------------------------
# Projects Settings
projects__settings:
  projects__title: Features
  projects__description: Everything to ensure effective real-time transaction and event monitoring.

#-------------------------------
# Footer Navigation Settings
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Software'
      url: 'https://github.com/jube-home/jube'
    - title: 'Documentation'
      url: 'https://jube-home.github.io/jube/'
    - title: 'Support'
      url: '/support/'

#-------------------------------
# Google Analytics
google-analytics: G-7PYZ045CND
